
# Forms
simsalabim/sisyphus: 
  :js: ""
  :css: ""
  :descr: "form:"
ivaynberg/select2: 
  :js: "select2.js"
  :css: "select2.css"
  :descr: "form:"
devluis/ddslick: 
  :js: "js/ddslick.js"
  :descr: "form:"

# Images
tapmodo/Jcrop:
  :js: "js/jquery.Jcrop.js"
  :css: "css/jquery.Jcrop.css"
  :img: "css/Jcrop.gif"
  :descr: "image:"
#it seems the many files feature is missing here
gilbitron/nivo-slider:
  :js: "jquery.nivo.slider.js"
  :css: "themes/default/default.css"
  :descr: "image:slider"

# Map
hpneo/gmaps:
  :js: "gmaps.js"
  :descr: "map:"

# Navigation
davist11/jquery-stickem:
  :js: "jquery.stickem.js"
  :descr: "navigation:"

# Essentials
scotthamper/cookies: 
  :js: "cookies.js"
  :descr: "essentials:"
briancherne/jquery-hoverintent:
  :js: "jquery.hoverIntent.js"
  :descr: "essentials:"

# Yup
arturadib/strapdown: 
  :js: "src/strapdown.js"
  :css: "src/strapdown.css"
  :desc: ""
